# This is a basic workflow to help you get started with Actions

name: Mainnet

# Controls when the action will run.
on:
  release:
    types: [released]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  node-version: 20

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ env.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.node-version }}
      - name: Install Yarn
        run: npm install -g yarn
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT
      # - uses: everpcpc/actions-cache@v2
      #   env:
      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     AWS_REGION: 'us-east-2'
      #   with:
      #     bucket: ${{ secrets.AWS_BUCKET_NAME }} # required
      #     path: |
      #       node_modules
      #       .cache
      #     key: ${{ runner.os }}/yarn/${{ hashFiles('**/yarn.lock') }}
      #     restore-keys: |
      #       ${{ runner.os }}/yarn/
      # - name: remove @oraichain/oraidex-common
      #   run: |
      #     rm -rf node_modules/@oraichain/oraidex-universal-swap/node_modules/@oraichain/oraidex-common
      #     rm -rf node_modules/@oraichain/oraiswap-v3/node_modules/@oraichain/oraidex-common
      - id: yarn-cache
        uses: actions/cache@v4
        with:
          path: |
            ${{ steps.yarn-cache-dir-path.outputs.dir }}
            node_modules
            node_modules/.cache
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-
      - name: Install Dependencies
        # if: steps.yarn-cache.outputs.cache-hit != 'true'
        # run: yarn install --ignore-scripts
        run: yarn install --frozen-lockfile
      - name: Copy env
        run: cp .env.example .env
      - name: Build Production
        run: yarn build
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          VITE_APP_SENTRY_ENVIRONMENT: production
          CI: false
      - name: Deploy to firebase
        run: yarn firebase deploy --only hosting:oraiswap --token ${{ secrets.FIREBASE_TOKEN }}
      - name: Send discord message
        uses: appleboy/discord-action@master
        with:
          webhook_id: ${{ secrets.DISCORD_WEBHOOK_ID }}
          webhook_token: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}
          username: 'GitBot [oraiswap-frontend]'
          message: 'Repo oraiswap-frontend has just published by ${{ github.event.head_commit.author.name }}'
